/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.cms.service;
import cn.zhuatech.cms.common.BusinessException; import cn.zhuatech.cms.dto.CmsDto.*; import cn.zhuatech.cms.model.*; import cn.zhuatech.cms.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class CmsService {
    private final ContentItemRepository orders; private final PublishRecordRepository reports; private final ComponentRepository component; private final ReviewTaskRepository reviewTasks; private final CurrentUserService current;
    public CmsService(ContentItemRepository orders,PublishRecordRepository reports,ComponentRepository component,ReviewTaskRepository reviewTasks,CurrentUserService current){this.orders=orders;this.reports=reports;this.component=component;this.reviewTasks=reviewTasks;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getSiteCode();List<ContentItem> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findBySiteCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<ContentItemView> contentItems(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){ContentItem order=orders.findById(id).orElseThrow(()->new BusinessException("内容任务不存在"));if(order.getStatus()==ContentItem.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new PublishRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<ContentItem> list){int planned=list.stream().mapToInt(ContentItem::getPlannedQty).sum(),done=list.stream().mapToInt(ContentItem::getCompletedQty).sum(),defects=list.stream().mapToInt(ContentItem::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日内容",String.format("%,d",planned),list.size()+" 张内容任务","blue"),new Metric("内容完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果合规率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("页面组件异常",component.countByStatus(Component.Status.ALARM)+"",reviewTasks.countByResult(ReviewTask.Result.PENDING)+" 项待审核","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),component.findAllByOrderByCodeAsc().stream().map(e->new ComponentView(e.getCode(),e.getName(),e.getSite().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),reviewTasks.findTop10ByOrderByIdDesc().stream().map(i->new ReviewTaskView(i.getReviewTaskNo(),i.getContentItem().getOrderNo(),i.getContentItem().getProductName(),i.getReviewTaskType(),i.getReviewTaskQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private ContentItemView view(ContentItem o){return new ContentItemView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getSite().getName(),o.getSite().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(ContentItem o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
